version: "3"
services:
  ydb:
    image: ghcr.io/nikitka/local-ydb:latest
    environment:
      - "YDB_DEFAULT_LOG_LEVEL=DEBUG"
      - "GRPC_TLS_PORT=2135"
      - "GRPC_PORT=2136"
      - "MON_PORT=8765"
      - "YDB_USE_IN_MEMORY_PDISKS=true"
      - "POSTGRES_USER=${YDB_PG_USER:-postgres}"
      - "POSTGRES_PASSWORD=${YDB_PG_PASSWORD:-password}"
    healthcheck:
      test: "/bin/sh /health_check"
      interval: 1s
      start_period: 10s
  project:
    image: ydb-test/psycopg2
    depends_on:
      ydb:
        condition: service_healthy
    environment:
      - PSYCOPG2_TESTDB=${YDB_PG_DATABASE:-/local}
      - PSYCOPG2_TESTDB_HOST=${YDB_PG_HOST:-ydb}
      - PSYCOPG2_TESTDB_PORT=${YDB_PG_PORT:-5432}
      - PSYCOPG2_TESTDB_USER=${YDB_PG_USER:-postgres}
      - PSYCOPG2_TESTDB_PASSWORD=${YDB_PG_PASSWORD:-password}
      - YDB_PG_TESTNAME=${YDB_PG_TESTNAME:-}
    build:
      context: .
      network: host
    volumes:
      - ./exchange:/exchange
      - ./test-result/:/test-result
